version: "3.9"
services:
  web:
    build: .
    ports:
      - "8081:80"
    restart: unless-stopped

  db_migrations:
    build: 
      context: ./
      dockerfile: Migrations/Dockerfile

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data:
    driver: local
